name: SpotReserve CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install
        working-directory: backend

      - name: Instalar Jest globalmente
        run: npm install -g jest
        working-directory: backend

      - name: Ejecutar pruebas con Jest global
        run: jest --forceExit
        working-directory: backend
